/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.judo;

import com.judo.datos.*;
import com.judo.dominio.*;
import static com.mycompany.judo.Judo.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alumno Mañana
 */
public class Clubs extends javax.swing.JFrame {

    /**
     * Creates new form Clubs
     */
    public Clubs() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        clb = new javax.swing.JComboBox<>();
        entre = new javax.swing.JCheckBox();
        compe = new javax.swing.JCheckBox();
        atras = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        buscar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana Pro Cond Black", 3, 36)); // NOI18N
        jLabel1.setText("CLUBS");

        clb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Budokan", "Mederre", "Ronnin", "Tsukiru", "Okami", "Jushirokan", "Bezana", "Mislata" }));

        entre.setText("Entrenador");

        compe.setText("Competidor");

        atras.setText("<");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(clb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(compe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(atras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(atras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entre)
                    .addComponent(compe)
                    .addComponent(buscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
            Menu ventana = new Menu();
            ventana.setVisible(true);
    }//GEN-LAST:event_atrasActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        
        
      int club = 0;

        switch(clb.getSelectedItem().toString()){
                
                case "Budokan":
                    club = clubs.get(0).getId_club();
                break;
                
                case "Mederre":
                    club = clubs.get(1).getId_club();
                break;
                
                case "Ronnin":
                    club = clubs.get(2).getId_club();
                break;
                
                case "Tsukiru":
                    club = clubs.get(3).getId_club();
                break;
                
                case "Okami":
                    club = clubs.get(4).getId_club();
                break;
                
                case "Jushirokan":
                    club = clubs.get(5).getId_club();
                break;
                
                case "Bezana":
                    club = clubs.get(6).getId_club();
                break;
                
                case "Mislata":
                    club = clubs.get(7).getId_club();
                break;
            }
        
        
        if (entre.isSelected() && compe.isSelected()){
            JOptionPane.showMessageDialog(null, "SOLO PUEDES SELECIONAR UNO A LA VEZ");
        }else if (compe.isSelected()) {
            ICompetidorDAO iclubDAO = new CompetidorDAO();   
            List<Competidor> clubs = iclubDAO.clubs(club);
            
            DefaultTableModel modelo = new DefaultTableModel();
        
            modelo.addColumn("ID_CLUB");
            modelo.addColumn("NOMBRE");
            modelo.addColumn("APELLIDO");

            String[] datos = new String[4];
            //Datos a mostrar en el jTable
            clubs.forEach(clu -> {
                datos[0] = String.valueOf(clu.getId_club());
                datos[1] = clu.getNombre();
                datos[2] = clu.getApellido();
                modelo.addRow(datos);
            });
            
            tabla.setModel(modelo);
         
            
        } else if (entre.isSelected()){
            IEntrenadorDAO iclubDAO = new EntrenadorDAO();   
            List<Entrenador> clubs = iclubDAO.clubs(club);
            
            DefaultTableModel modelo = new DefaultTableModel();
        
            modelo.addColumn("ID_CLUB");
            modelo.addColumn("NOMBRE");
            modelo.addColumn("APELLIDO");

            String[] datos = new String[4];
            //Datos a mostrar en el jTable
            clubs.forEach(clu -> {
                datos[0] = String.valueOf(clu.getId_club());
                datos[1] = clu.getNombre();
                datos[2] = clu.getApellido();
                modelo.addRow(datos);
            });
            
            tabla.setModel(modelo) ;
        }else{
            JOptionPane.showMessageDialog(null, "DEBES SELECCIONAR COMPETIDOR O ENTRENADOR");
        }
 
        
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clubs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton buscar;
    private javax.swing.JComboBox<String> clb;
    private javax.swing.JCheckBox compe;
    private javax.swing.JCheckBox entre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
