/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.judo;

import com.judo.datos.CompetidorDAO;
import com.judo.datos.ICompetidorDAO;
import com.judo.dominio.Competidor;
import static com.mycompany.judo.Judo.*;
import static com.mycompany.judo.Judo.copa;
import static com.mycompany.judo.Judo.count;
import static com.mycompany.judo.Judo.pesos;
import java.awt.Image;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno Mañana
 */
public class CompetirLucha1 extends javax.swing.JFrame {

    /**
     * Creates new form CompetirLucha
     */
    public CompetirLucha1() {
        initComponents();
        this.setLocationRelativeTo(null);
        nombrecopa.setText(copa);
        tecnica1.setText(competidor.getTecnicas()[0].getNombre());
        tecnica2.setText(competidor.getTecnicas()[1].getNombre());
        
        combate.setText("COMBATE 1");
        competidor1.setText(competidor.getNombre());
        
        int id = 0;
        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i).getId_competidor() == competidor.getId_competidor()) {
                id = i;
            }
        }
        
        lista.remove(id);
        
        numero1 = (int) (Math.random() * lista.size() );
        while (lista.size() < numero1) {
            numero1 = (int) (Math.random() * lista.size() );
        }
        
        numeros[0] = numero1;
        competidor2.setText(lista.get(numero1).getNombre());
        lista.remove(lista.get(numero1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        foto = new javax.swing.JLabel();
        nombrecopa = new javax.swing.JLabel();
        competidor1 = new javax.swing.JLabel();
        competidor2 = new javax.swing.JLabel();
        tecnica1 = new javax.swing.JButton();
        tecnica2 = new javax.swing.JButton();
        combate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 410, 220));

        nombrecopa.setFont(new java.awt.Font("Verdana Pro Cond Black", 3, 36)); // NOI18N
        nombrecopa.setText("jLabel1");
        jPanel1.add(nombrecopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        competidor1.setFont(new java.awt.Font("Verdana Pro Cond Light", 1, 18)); // NOI18N
        competidor1.setText("jLabel1");
        jPanel1.add(competidor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        competidor2.setFont(new java.awt.Font("Verdana Pro Cond Light", 1, 18)); // NOI18N
        competidor2.setText("jLabel2");
        jPanel1.add(competidor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        tecnica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecnica1ActionPerformed(evt);
            }
        });
        jPanel1.add(tecnica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, 17));

        tecnica2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecnica2ActionPerformed(evt);
            }
        });
        jPanel1.add(tecnica2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, 20));

        combate.setText("jLabel3");
        jPanel1.add(combate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tecnica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecnica1ActionPerformed
        // TODO add your handling code here:


        int num = (int) (Math.random());
        int vida1 = 0, vida2 = 0, resultado = 0, resultado2 = 0;
        int danio1 = competidor.getTecnicas()[0].getProbabilidad();
        int danio2 = competidores.get(numero1).getTecnicas()[num].getProbabilidad();
        int def1 = competidor.getTecnicas()[0].getDefensa();
        int def2 = competidores.get(numero1).getTecnicas()[num].getDefensa();

        vida1 = Math.abs(def1 - danio2);
        vida2 = Math.abs(def2 - danio1);

        if (vida1 >= 0 && vida1 <= 30) {
            ImageIcon enemy_img = new ImageIcon("src\\main\\java\\img\\ippon.jpg");
            Icon enemy = new ImageIcon(enemy_img.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT));
            foto.setIcon(enemy);
            JOptionPane.showMessageDialog(null, "IPPON TUYO");
            foto.setIcon(null);
            resultado = 2;
        } else if (vida1 >= 31 && vida1 <= 60) {
            puntos1++;
            if (puntos1 == 2) {
                ImageIcon enemy_img = new ImageIcon("src\\main\\java\\img\\ippon.jpg");
                Icon enemy = new ImageIcon(enemy_img.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT));
                foto.setIcon(enemy);
                JOptionPane.showMessageDialog(null, "WAZA-RY WAZA-TE IPPON TUYO");
                foto.setIcon(null);
                resultado = 2;
            } else {
                ImageIcon enemy_img = new ImageIcon("src\\main\\java\\img\\wazary.jpg");
                Icon enemy = new ImageIcon(enemy_img.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT));
                foto.setIcon(enemy);
                JOptionPane.showMessageDialog(null, "WAZA-RY TUYO");
                foto.setIcon(null);
            }
        } else if (vida1 >= 61 && vida1 <= 100) {
            ImageIcon enemy_img = new ImageIcon("src\\main\\java\\img\\nada.jpg");
            Icon enemy = new ImageIcon(enemy_img.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT));
            foto.setIcon(enemy);
            JOptionPane.showMessageDialog(null, "NO HA SIDO NADA");
            foto.setIcon(null);
            competidor.relleno_tecnicas(tecnicas);
        } else if (vida2 >= 0 && vida2 <= 30) {
            ImageIcon enemy_img = new ImageIcon("src\\main\\java\\img\\ippon2.jpg");
            Icon enemy = new ImageIcon(enemy_img.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT));
            foto.setIcon(enemy);
            JOptionPane.showMessageDialog(null, "IPPON DEL CONTRINCANTE");
            foto.setIcon(null);
            resultado2 = 2;
        } else if (vida2 >= 31 && vida2 <= 60) {
            puntos2++;
            if (puntos2 == 2) {
                ImageIcon enemy_img = new ImageIcon("src\\main\\java\\img\\ippon2.jpg");
                Icon enemy = new ImageIcon(enemy_img.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT));
                foto.setIcon(enemy);
                JOptionPane.showMessageDialog(null, "WAZA-RY WAZA_TE IPPONDEL CONTRINCANTE");
                foto.setIcon(null);
                resultado2 = 2;
            } else {
                ImageIcon enemy_img = new ImageIcon("src\\main\\java\\img\\wazary2.jpg");
                Icon enemy = new ImageIcon(enemy_img.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT));
                foto.setIcon(enemy);
                JOptionPane.showMessageDialog(null, "WAZA-RY DEL CONTRINCANTE");
                foto.setIcon(null);
            }
        } else if (vida2 >= 61 && vida2 <= 100 && vida2 < vida1) {
            ImageIcon enemy_img = new ImageIcon("src\\main\\java\\img\\nada2.jpg");
            Icon enemy = new ImageIcon(enemy_img.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT));
            foto.setIcon(enemy);
            JOptionPane.showMessageDialog(null, "NO HA SIDO NADA");
            foto.setIcon(null);
             competidor.relleno_tecnicas(tecnicas);
        }

        if (resultado == 2) {
            count++;
            CompetirLucha2 ventana = new CompetirLucha2();
            this.setVisible(false);
            ventana.setVisible(true);
            
        } else if (resultado2 == 2) {
            count = 3;
            JOptionPane.showMessageDialog(null, "HAS QEUDADO 5º");
            Menu ventana = new Menu();
            this.setVisible(false);
            ventana.setVisible(true);
            puntos1 = 0;
            puntos2 = 0;
            puntos3 = 0;
            puntos4 = 0;
            puntos5 = 0;
            puntos6 = 0;
            lista = ilistaDAO.lista(competidor.getPeso());
            for (int i = 0; i < numeros.length; i++) {
                numeros[i] = 0;
            }
            
        }


    }//GEN-LAST:event_tecnica1ActionPerformed

    private void tecnica2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecnica2ActionPerformed
        // TODO add your handling code here:

        int num = (int) (Math.random());
        int vida1 = 0, vida2 = 0, resultado = 0, resultado2 = 0;
        int danio1 = competidor.getTecnicas()[0].getProbabilidad();
        int danio2 = competidores.get(numero1).getTecnicas()[num].getProbabilidad();
        int def1 = competidor.getTecnicas()[0].getDefensa();
        int def2 = competidores.get(numero1).getTecnicas()[num].getDefensa();

        vida1 = Math.abs(def1 - danio2);
        vida2 = Math.abs(def2 - danio1);

        if (vida1 >= 0 && vida1 <= 30) {
            ImageIcon enemy_img = new ImageIcon("src\\main\\java\\img\\ippon.jpg");
            Icon enemy = new ImageIcon(enemy_img.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT));
            foto.setIcon(enemy);
            JOptionPane.showMessageDialog(null, "IPPON TUYO");
            foto.setIcon(null);
            resultado = 2;
        } else if (vida1 >= 31 && vida1 <= 60) {
            puntos1++;
            if (puntos1 == 2) {
                ImageIcon enemy_img = new ImageIcon("src\\main\\java\\img\\ippon.jpg");
                Icon enemy = new ImageIcon(enemy_img.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT));
                foto.setIcon(enemy);
                JOptionPane.showMessageDialog(null, "WAZA-RY WAZA-TE IPPON TUYO");
                foto.setIcon(null);
                resultado = 2;
            } else {
                ImageIcon enemy_img = new ImageIcon("src\\main\\java\\img\\wazary.jpg");
                Icon enemy = new ImageIcon(enemy_img.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT));
                foto.setIcon(enemy);
                JOptionPane.showMessageDialog(null, "WAZA-RY TUYO");
                foto.setIcon(null);
            }
        } else if (vida1 >= 61 && vida1 <= 100) {
            ImageIcon enemy_img = new ImageIcon("src\\main\\java\\img\\nada.jpg");
            Icon enemy = new ImageIcon(enemy_img.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT));
            foto.setIcon(enemy);
            JOptionPane.showMessageDialog(null, "NO HA SIDO NADA");
            foto.setIcon(null);
             competidor.relleno_tecnicas(tecnicas);
        } else if (vida2 >= 0 && vida2 <= 30) {
            ImageIcon enemy_img = new ImageIcon("src\\main\\java\\img\\ippon2.jpg");
            Icon enemy = new ImageIcon(enemy_img.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT));
            foto.setIcon(enemy);
            JOptionPane.showMessageDialog(null, "IPPON DEL CONTRINCANTE");
            foto.setIcon(null);
            resultado2 = 2;
        } else if (vida2 >= 31 && vida2 <= 60) {
            puntos2++;
            if (puntos2 == 2) {
                ImageIcon enemy_img = new ImageIcon("src\\main\\java\\img\\ippon2.jpg");
                Icon enemy = new ImageIcon(enemy_img.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT));
                foto.setIcon(enemy);
                JOptionPane.showMessageDialog(null, "WAZA-RY WAZA_TE IPPONDEL CONTRINCANTE");
                foto.setIcon(null);
                resultado2 = 2;
            } else {
                ImageIcon enemy_img = new ImageIcon("src\\main\\java\\img\\wazary2.jpg");
                Icon enemy = new ImageIcon(enemy_img.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT));
                foto.setIcon(enemy);
                JOptionPane.showMessageDialog(null, "WAZA-RY DEL CONTRINCANTE");
                foto.setIcon(null);
            }
        } else if (vida2 >= 61 && vida2 <= 100 && vida2 < vida1) {
            ImageIcon enemy_img = new ImageIcon("src\\main\\java\\img\\nada2.jpg");
            Icon enemy = new ImageIcon(enemy_img.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT));
            foto.setIcon(enemy);
            JOptionPane.showMessageDialog(null, "NO HA SIDO NADA");
            foto.setIcon(null);
             competidor.relleno_tecnicas(tecnicas);
        }

        if (resultado == 2) {
            count++;
            CompetirLucha2 ventana = new CompetirLucha2();
            this.setVisible(false);
            ventana.setVisible(true);
           
        } else if (resultado2 == 2) {
            count = 3;
            JOptionPane.showMessageDialog(null, "HAS QEUDADO 5º");
            Menu ventana = new Menu();
            this.setVisible(false);
            ventana.setVisible(true);
            puntos1 = 0;
            puntos2 = 0;
            puntos3 = 0;
            puntos4 = 0;
            puntos5 = 0;
            puntos6 = 0;
            lista = ilistaDAO.lista(competidor.getPeso());
            for (int i = 0; i < numeros.length; i++) {
                numeros[i] = 0;
            }
         
        }

    }//GEN-LAST:event_tecnica2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompetirLucha1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompetirLucha1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompetirLucha1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompetirLucha1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompetirLucha1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel combate;
    private javax.swing.JLabel competidor1;
    private javax.swing.JLabel competidor2;
    private javax.swing.JLabel foto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombrecopa;
    private javax.swing.JButton tecnica1;
    private javax.swing.JButton tecnica2;
    // End of variables declaration//GEN-END:variables
}
