/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.judo;

import static com.mycompany.judo.Judo.clubs;
import static com.mycompany.judo.Judo.competidor;
import static com.mycompany.judo.Judo.competidores;
import static com.mycompany.judo.Judo.icompetidorDAO;
import static com.mycompany.judo.Judo.pesos;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno Mañana
 */
public class Modificar extends javax.swing.JFrame {

    /**
     * Creates new form Modificar
     */
    public Modificar() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        registrarse = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        contrasenia = new javax.swing.JPasswordField();
        club = new javax.swing.JComboBox<>();
        peso = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana Pro Cond Black", 3, 36)); // NOI18N
        jLabel1.setText("USUARIO");

        atras.setText("<");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        jLabel5.setText("Contraseña");

        registrarse.setText("Modificar");
        registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseActionPerformed(evt);
            }
        });

        jLabel6.setText("Apellido");

        jLabel7.setText("Peso");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        contrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseniaActionPerformed(evt);
            }
        });

        club.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Budokan", "Mederre", "Ronnin", "Tsukiru", "Okami", "Jushirokan", "Bezana", "Mislata" }));

        peso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "66", "73", "81", "91", "100", "101", "52", "57", "63", "70", "78", "79" }));

        jLabel2.setText("Usuario");

        jLabel3.setText("Nombre");

        jLabel4.setText("Club");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(112, 112, 112)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(atras)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(registrarse))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(club, 0, 1, Short.MAX_VALUE)
                                    .addComponent(usuario)
                                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(apellido)
                                    .addComponent(contrasenia)
                                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(atras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(club, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(registrarse)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        
         this.setVisible(false);
            Usuario ventana = new Usuario();
            ventana.setVisible(true);
    }//GEN-LAST:event_atrasActionPerformed

    private void registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseActionPerformed
        // TODO add your handling code here:

        String usu = usuario.getText();
        String clave = String.valueOf(contrasenia.getPassword());
        String nom = nombre.getText();
        String apell = apellido.getText();
        String clb = club.getSelectedItem().toString();
        int ps = Integer.parseInt(peso.getSelectedItem().toString());
        boolean op1 = false;
        int idusuario = competidores.get(competidores.size()-1).getId_competidor();
        int idclub = -1;
        int idpeso = -1;

        //        Competicion compe = new Competicion(1,"Copa Canarias", "Tenerife");
        //        compeDAO.insertar(compe);

        for (int i = 0; i < competidores.size(); i++) {
            if (usu.equals(competidores.get(i).getUsuario())) {
                op1 = true;
                JOptionPane.showMessageDialog(null, "EL USUARIO YA EXISTE");
            }
        }

        if (op1 == false) {

            //SETTEAR TODOS LOS PARAMETROS
            competidor.setId_competidor(idusuario+1);
            competidor.setNombre(nom);
            competidor.setApellido(apell);
            competidor.setClave(clave);
            competidor.setUsuario(usu);

            //SETTEAR EL ID DEL CLUB
            switch(clb){

                case "Budokan":
                idclub = clubs.get(0).getId_club();
                competidor.setId_club(idclub);
                break;

                case "Mederre":
                idclub = clubs.get(1).getId_club();
                competidor.setId_club(idclub);
                break;

                case "Ronnin":
                idclub = clubs.get(2).getId_club();
                competidor.setId_club(idclub);
                break;

                case "Tsukiru":
                idclub = clubs.get(3).getId_club();
                competidor.setId_club(idclub);
                break;

                case "Okami":
                idclub = clubs.get(4).getId_club();
                competidor.setId_club(idclub);
                break;

                case "Jushirokan":
                idclub = clubs.get(5).getId_club();
                competidor.setId_club(idclub);
                break;

                case "Bezana":
                idclub = clubs.get(6).getId_club();
                competidor.setId_club(idclub);
                break;

                case "Mislata":
                idclub = clubs.get(7).getId_club();
                competidor.setId_club(idclub);
                break;
            }

            //SETTEAR EL ID DEL PESO
            switch(ps){

                case 66:
                idpeso = pesos.get(0).getId_peso();
                competidor.setPeso(idpeso);
                break;

                case 73:
                idpeso = pesos.get(1).getId_peso();
                competidor.setPeso(idpeso);
                break;

                case 81:
                idpeso = pesos.get(2).getId_peso();
                competidor.setPeso(idpeso);
                break;

                case 91:
                idpeso = pesos.get(3).getId_peso();
                competidor.setPeso(idpeso);
                break;

                case 100:
                idpeso = pesos.get(4).getId_peso();
                competidor.setPeso(idpeso);
                break;

                case 101:
                idpeso = pesos.get(5).getId_peso();
                competidor.setPeso(idpeso);
                break;

                case 52:
                idpeso = pesos.get(6).getId_peso();
                competidor.setPeso(idpeso);
                break;

                case 57:
                idpeso = pesos.get(7).getId_peso();
                competidor.setPeso(idpeso);
                break;

                case 63:
                idpeso = pesos.get(8).getId_peso();
                competidor.setPeso(idpeso);
                break;

                case 70:
                idpeso = pesos.get(9).getId_peso();
                competidor.setPeso(idpeso);
                break;

                case 78:
                idpeso = pesos.get(10).getId_peso();
                competidor.setPeso(idpeso);
                break;

                case 79:
                idpeso = pesos.get(11).getId_peso();
                competidor.setPeso(idpeso);
                break;
            }
            
            if ("".equals(usu) || "".equals(nom) || "".equals(apell) || "".equals(clave) || idclub == 0 || idpeso == 0) {
                JOptionPane.showMessageDialog(null, "RECUERDA QUE TODOS LOS CAMPOS DEBEN ESTAR RELLENOS");
            }else{
                icompetidorDAO.actualizar(competidor);
            
                competidores = icompetidorDAO.mostrartodo();
            }

          

            this.setVisible(false);
            Menu ventana = new Menu();
            ventana.setVisible(true);
        }

    }//GEN-LAST:event_registrarseActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void contraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseniaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JButton atras;
    private javax.swing.JComboBox<String> club;
    private javax.swing.JPasswordField contrasenia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> peso;
    private javax.swing.JButton registrarse;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
