/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.judo;

import com.judo.datos.CompetidorDAO;
import com.judo.datos.ICompetidorDAO;
import com.judo.dominio.Competidor;
import static com.mycompany.judo.Judo.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alumno Mañana
 */
public class Rankings extends javax.swing.JFrame {

    /**
     * Creates new form Rankings
     */
    public Rankings() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        buscar = new javax.swing.JButton();
        ps = new javax.swing.JComboBox<>();
        atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 135, 361, 159));

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        ps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "66", "73", "81", "91", "100", "101", "52", "57", "63", "70", "78", "79" }));
        jPanel1.add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        atras.setText("<");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana Pro Cond Black", 3, 36)); // NOI18N
        jLabel1.setText("RANKINGS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 38, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        Menu ventana = new Menu();
        ventana.setVisible(true);
    }//GEN-LAST:event_atrasActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
         
        int id = 0;
                
        switch(ps.getSelectedIndex()){

                case 0:
                    id = pesos.get(0).getId_peso();
                break;
                
                case 1:
                    id = pesos.get(1).getId_peso();
                break;
                
                case 2:
                   id = pesos.get(2).getId_peso();
                break;
                
                case 3:
                    id = pesos.get(3).getId_peso();
                break;
                
                case 4:
                    id = pesos.get(4).getId_peso();
                break;
                
                case 5:
                    id = pesos.get(5).getId_peso();
                break;
                
                case 6:
                    id = pesos.get(6).getId_peso();
                break;
                
                case 7:
                    id = pesos.get(7).getId_peso();
                break;
                
                case 8:
                    id = pesos.get(8).getId_peso();
                break;
                
                case 9:
                    id = pesos.get(9).getId_peso();
                break;
                
                case 10:
                    id = pesos.get(10).getId_peso();
                break;
                
                case 11:
                    id = pesos.get(11).getId_peso();
                break;
            }
        
        ICompetidorDAO irankingDAO = new CompetidorDAO();   
        List<Competidor> rankings = irankingDAO.ranking(id);
        
         DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("PUNTOS");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("APELLIDO");
        
        
        String[] datos = new String[4];
        //Datos a mostrar en el jTable
        rankings.forEach(rankin -> {
           datos[0] = String.valueOf(rankin.getPuntos());
           datos[1] = rankin.getNombre();
           datos[2] = rankin.getApellido();
           modelo.addRow(datos);
        });
        tabla.setModel(modelo);
        
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rankings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rankings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rankings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rankings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rankings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> ps;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
