/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.judo;
import com.judo.dominio.Competidor;
import static com.mycompany.judo.Judo.*;
import com.judo.datos.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno Mañana
 */
public class Registrarse extends javax.swing.JFrame {

    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        registrarse = new javax.swing.JButton();
        usuario = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        contrasenia = new javax.swing.JPasswordField();
        club = new javax.swing.JComboBox<>();
        peso = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana Pro Cond Black", 3, 36)); // NOI18N
        jLabel1.setText("REGISTRARSE");

        registrarse.setText("Registrarse");
        registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseActionPerformed(evt);
            }
        });

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        contrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseniaActionPerformed(evt);
            }
        });

        club.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Budokan", "Mederre", "Ronnin", "Tsukiru", "Okami", "Jushirokan", "Bezana", "Mislata" }));

        peso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "66", "73", "81", "91", "100", "101", "52", "57", "63", "70", "78", "79" }));

        jLabel2.setText("Usuario");

        jLabel3.setText("Nombre");

        jLabel4.setText("Club");

        jLabel5.setText("Contraseña");

        jLabel6.setText("Apellido");

        jLabel7.setText("Peso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(registrarse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(club, 0, 1, Short.MAX_VALUE)
                    .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(nombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(apellido)
                    .addComponent(contrasenia)
                    .addComponent(peso, 0, 88, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(club, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(registrarse)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void contraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseniaActionPerformed

    private void registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseActionPerformed
        // TODO add your handling code here:
        
        String usu = usuario.getText();
        String clave = String.valueOf(contrasenia.getPassword());
        String nom = nombre.getText();
        String apell = apellido.getText();
        String clb = club.getSelectedItem().toString();
        int ps = Integer.parseInt(peso.getSelectedItem().toString());
        boolean op1 = false;
        int idusuario = competidores.get(competidores.size()-1).getId_competidor();
        int idclub = 0;
        int idpeso = 0;
        
        

        //        Competicion compe = new Competicion(1,"Copa Canarias", "Tenerife");
        //        compeDAO.insertar(compe);
        
        for (int i = 0; i < competidores.size(); i++) {
            if (usu.equals(competidores.get(i).getUsuario())) {
                op1 = true;
                JOptionPane.showMessageDialog(null, "EL USUARIO YA EXISTE");
            } 
        }
        
        
       
        if (op1 == false) {
            
            //SETTEAR TODOS LOS PARAMETROS
            competidor.setId_competidor(idusuario+1);
            competidor.setNombre(nom);
            competidor.setApellido(apell);
            competidor.setClave(clave);
            competidor.setUsuario(usu);

            //SETTEAR EL ID DEL CLUB
            switch(clb){
                
                case "Budokan":
                    idclub = clubs.get(0).getId_club();
                    competidor.setId_club(idclub);
                break;
                
                case "Mederre":
                    idclub = clubs.get(1).getId_club();
                    competidor.setId_club(idclub);
                break;
                
                case "Ronnin":
                    idclub = clubs.get(2).getId_club();
                    competidor.setId_club(idclub);
                break;
                
                case "Tsukiru":
                    idclub = clubs.get(3).getId_club();
                    competidor.setId_club(idclub);
                break;
                
                case "Okami":
                    idclub = clubs.get(4).getId_club();
                    competidor.setId_club(idclub);
                break;
                
                case "Jushirokan":
                    idclub = clubs.get(5).getId_club();
                    competidor.setId_club(idclub);
                break;
                
                case "Bezana":
                    idclub = clubs.get(6).getId_club();
                    competidor.setId_club(idclub);
                break;
                
                case "Mislata":
                    idclub = clubs.get(7).getId_club();
                    competidor.setId_club(idclub);
                break;
            }
            
            //SETTEAR EL ID DEL PESO
            switch(ps){
                
                case 66:
                    idpeso = pesos.get(0).getId_peso();
                    competidor.setPeso(idpeso);
                break;
                
                case 73:
                    idpeso = pesos.get(1).getId_peso();
                    competidor.setPeso(idpeso);
                break;
                
                case 81:
                    idpeso = pesos.get(2).getId_peso();
                    competidor.setPeso(idpeso);
                break;
                
                case 91:
                    idpeso = pesos.get(3).getId_peso();
                    competidor.setPeso(idpeso);
                break;
                
                case 100:
                    idpeso = pesos.get(4).getId_peso();
                    competidor.setPeso(idpeso);
                break;
                
                case 101:
                    idpeso = pesos.get(5).getId_peso();
                    competidor.setPeso(idpeso);
                break;
                
                case 52:
                    idpeso = pesos.get(6).getId_peso();
                    competidor.setPeso(idpeso);
                break;
                
                case 57:
                    idpeso = pesos.get(7).getId_peso();
                    competidor.setPeso(idpeso);
                break;
                
                case 63:
                    idpeso = pesos.get(8).getId_peso();
                    competidor.setPeso(idpeso);
                break;
                
                case 70:
                    idpeso = pesos.get(9).getId_peso();
                    competidor.setPeso(idpeso);
                break;
                
                case 78:
                    idpeso = pesos.get(10).getId_peso();
                    competidor.setPeso(idpeso);
                break;
                
                case 79:
                    idpeso = pesos.get(11).getId_peso();
                    competidor.setPeso(idpeso);
                break;
            }

            icompetidorDAO.insertar(competidor);
            
            competidores.add(competidor);
            
            lista = ilistaDAO.lista(competidor.getPeso());
            
            this.setVisible(false);
            Menu ventana = new Menu();
            ventana.setVisible(true);
        } 
 
    }//GEN-LAST:event_registrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JComboBox<String> club;
    private javax.swing.JPasswordField contrasenia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> peso;
    private javax.swing.JButton registrarse;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
